# Generated by Django 4.1.1 on 2022-10-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0005_question_deleted_question_deleted_by_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='deleted',
            field=models.DateTimeField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_by_cascade',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
