# Generated by Django 4.1.1 on 2022-10-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_learnedword'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnedword',
            name='answer',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
